# Generated by Django 3.2.24 on 2024-02-14 18:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uso', models.CharField(max_length=100)),
                ('area_predio', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
