# Generated by Django 3.2.24 on 2024-02-15 16:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240215_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('osm_id', models.BigIntegerField(default=0)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_of_streets', to='backend.node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_of_streets', to='backend.node')),
            ],
        ),
        migrations.CreateModel(
            name='StreetNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('h5_file', models.FileField(blank=True, null=True, upload_to='media/h5_files/')),
                ('tags', models.JSONField(blank=True, null=True)),
                ('streets', models.ManyToManyField(to='backend.Street')),
            ],
        ),
    ]
