# Generated by Django 3.2.24 on 2024-02-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_node_street_streetnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_of_street', to='backend.node'),
        ),
        migrations.AlterField(
            model_name='street',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_of_street', to='backend.node'),
        ),
    ]
