# Generated by Django 3.2.24 on 2024-02-15 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20240215_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('geo_field', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RenameField(
            model_name='areaofinterest',
            old_name='geometry',
            new_name='geo_field',
        ),
        migrations.RenameField(
            model_name='discretedistribution',
            old_name='geometry',
            new_name='geo_field',
        ),
        migrations.RenameField(
            model_name='landuse',
            old_name='geometry',
            new_name='geo_field',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='geometry',
            new_name='geo_field',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='geometry',
            new_name='geo_field',
        ),
    ]
