# Generated by Django 3.2.24 on 2024-02-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20240215_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
