version: '3.8'

services:
  db:
    container_name: clbb_db
    image: postgis/postgis
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: clbb
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clbb

  web:
    container_name: clbb_api
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
      - ./api/assets:/app/assets
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - clbb

volumes:
  postgres_data:

networks:
  clbb:
    external: true