version: '3.8'

services:
  db:
    container_name: clbb_db
    image: postgis/postgis
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: clbb
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
      - ./assets:/app/assets
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    #   DATABASE_HOST: db
    #   DATABASE_NAME: geodb
    #   DATABASE_USER: clbb
    #   DATABASE_PASSWORD: pass123

volumes:
  postgres_data:
