# Generated by Django 3.2.24 on 2024-02-15 03:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_areaofinterest_discretedistribution'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='backend.areaofinterest'),
        ),
        migrations.AddField(
            model_name='project',
            name='discrete_distributions',
            field=models.ManyToManyField(blank=True, to='backend.DiscreteDistribution'),
        ),
        migrations.AddField(
            model_name='project',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='plates',
            field=models.ManyToManyField(blank=True, to='interactive.Plate'),
        ),
    ]
