# Generated by Django 3.2.24 on 2024-02-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_auto_20240215_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='geometry',
        ),
    ]
