# Generated by Django 3.2.24 on 2024-02-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_node_street_streetnetwork'),
        ('interactive', '0003_remove_project_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='street_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.streetnetwork'),
        ),
    ]
